# Generated by Django 3.2.16 on 2023-01-15 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_recipe_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='price',
        ),
    ]
